# Generated by Django 4.0.5 on 2022-06-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webpage',
            table='webpage',
        ),
        migrations.AlterModelTable(
            name='website',
            table='website',
        ),
        migrations.AlterModelTable(
            name='websitecategory',
            table='website_category',
        ),
    ]
